project_id = "esnrwamfmjiwwftdiign"

[functions.voice-to-text]
verify_jwt = false

[functions.diagnosis-analysis]
verify_jwt = false

[functions.realtime-voice-chat]
verify_jwt = false

[functions.simple-chat]
verify_jwt = false