// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esnrwamfmjiwwftdiign.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbnJ3YW1mbWppd3dmdGRpaWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDA1OTEsImV4cCI6MjA2NzI3NjU5MX0.htyMOWBqQhDYUmJarMxqtwo391IEMLY1YwXBccMAacQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});